### ISSUE TITLE
aboout dataset 

### ISSUE THREAD

**Issue by yinyang472** [XuelianCheng/HybridStereoNet#1]
can you share the scared dataset? If you can  please contact 289475058@qq.com.

**Comment by XuelianCheng** [comment]
HI, 

For SCARED 2019, unfortunately, you need to contact the dataset officer. We have signed their rules and can't send the data to others.

**Comment by yinyang472** [comment]
Thanks for your reply. I have&nbsp; signed the rules&nbsp; and send them&nbsp; to officer. But they did not contact me. it seems that the competition is closed. But I truely need it&nbsp; for my&nbsp;experiment, can you tell me other ways to get the dataset. 如果可以的话 可以添加一下的微信么 19922607059 .


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XuelianCheng/HybridStereoNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月10日(星期一) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XuelianCheng/HybridStereoNet] aboout dataset  (Issue #1)





 
HI,
 
For SCARED 2019, unfortunately, you need to contact the dataset officer. We have signed their rules and can't send the data to others.

**Comment by slowym** [comment]
how to get the dataset  ? Thanks

**Comment by XuelianCheng** [comment]
Hi，

Download [SCARED dataset](https://endovissub2019-scared.grand-challenge.org/Home/). To obtain a link to the data and code release, sign the challenge rules and email them to max.allan@intusurg.com. You will receive a temporary link to download the data and code.
